### ISSUE TITLE
MongoDB connections / exceeded your threshold

### ISSUE THREAD

**Issue by haydenpitout** [HamedBahram/next-pagination#1]
@HamedBahram 

I love your work ... !!!

Just a comment relating to movies.ts ... I notice using your implementation that my MongoDB connections quickly started to ramp up. And I started getting "connections to your cluster(s) have exceeded your threshold" type emails from Mongo.

The culprit appears to be the async call to `await init()`.

`(async () => {
  await init()
})()`

After commenting that out ... my number of connections literally fell off a cliff. Screenshot below.

Cheers, H

<img width="1301" alt="image" src="https://github.com/HamedBahram/next-pagination/assets/741577/9acca98d-de71-40c9-921a-5492e0b54340">

**Comment by HamedBahram** [comment]
@haydenpitout 

Thanks for flagging that! I'll update the code.
